// <auto-generated />
using BeatStreamr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BeatStreamr.Migrations
{
    [DbContext(typeof(BeatStreamrContext))]
    [Migration("20171206224146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BeatStreamr.Models.Album", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumArtFilePath");

                    b.Property<int>("ArtisID");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("BeatStreamr.Models.Beat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlbumID");

                    b.Property<string>("ArtFilePath");

                    b.Property<int>("ArtistID");

                    b.Property<decimal>("BPM");

                    b.Property<string>("BeatFilePath");

                    b.Property<TimeSpan?>("Duration");

                    b.Property<string>("Key");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Beat");
                });

            modelBuilder.Entity("BeatStreamr.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HeaderImagePath");

                    b.Property<string>("Name");

                    b.Property<string>("ProfileImagePath");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
